name: Run Python script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip' 
      run: pip install -r requirements.txt

    - name: Install dependencies
      run: pip install -r .github/workflows/requirements.txt; fi

    - name: Run script
      run: ls -la .github/workflows/

    - name: Run script
      run: python .github/workflows/twitter.py

